### ISSUE TITLE
silk_arc not working properly for gEDA

### ISSUE THREAD

**Issue by otanx** [dlharmon/footgen#11]
Hi,

the method silk_arc in geda.py is not working correctly.
Here is a solution that works for me:

    def silk_arc(self, x1, y1, x2, y2, angle, layer = 'F.SilkS', width = 0.15):
        ##
        # x1,y1: center of arc
        # x2,y2: starting point of drawing the arc, i.e. radius is distance between xy1 and xy2
        if "x" in self.mirror:
            x1 *= -1.0
            x2 *= -1.0
        if "y" in self.mirror:
            y1 *= -1.0
            y2 *= -1.0
            
        dx, dy = x2-x1, y2-y1
        # calculate radius
        r = math.sqrt(dx*dx + dy*dy)

        # start angle
        start = math.degrees(math.atan2(dy, dx))

        # sweep angle
        alpha = math.radians(angle)

        self._silk_arc(x1, y1, r, r, start, angle, width)

**Comment by dlharmon** [comment]
I incorporated this and added a test footprint using silk_arc with gEDA in commit 7d2f9d82af4ca0c9f1e6fd2e3d2f050b7d3c02a8
