### ISSUE TITLE
curious why attributes were removed?

### ISSUE THREAD

**Issue by miloh** [dlharmon/footgen#12]
Hi,

In f26496 some attributes were removed, including  rowofpads() which I use with footgen to generate families of smt connectors with symmetric single column/rows of pads.  

Is this row of pads generation function duplicated or available elsewhere? 

I checked sm_pads() thinking it may work like dip() to create single rows using with the right operator value, but I couldn't find a way to get it working.

**Comment by dlharmon** [comment]
Footgen is mainly a tool for my own use and the interfaces may change at times. It's probably best to create something like soh() for this. sm_pads() will likely be removed in a big refactor coming in the near future.
